# Numpy practice for beginners

These are some easy exercises to review some basic skills. If possible, use the numpy functions instead of native python code. 

In [ ]:
# First load the library
import numpy as np

## Execrise 1. 

Store the vector $(1,2,3)$ in a numpy array: first as a row vector, then as a column vector. Then compute the dot product of these two vectors.

In [ ]:
x = np.array([1,2,3])
y = np.array([[1],[2],[3]])
print(x)
print(y)
# 
print(x@y)
print(np.dot(x,y))

[1 2 3]
[[1]
 [2]
 [3]]
[14]
[14]


## Exercise 2

Create the integer matrices
$$
x = \left(
\begin{matrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 
\end{matrix}
\right)
,
y = \left(
\begin{matrix}
1 & 2 & 3  \\
4 & 5 & 6  \\
7 & 8 & 9 \\
10 & 11 & 12 
\end{matrix}
\right).
$$
Describe each matrix, i.e., find its shape, size and dimensions. Print the element located in row 3 column 2 in each case. Then find the matrix products $x\cdot y$ and $y \cdot x$. Find the minimum and maximum entry in $x$. Then find the minimum entry in each column of $x$. Then find the average and the median entry in $x$.

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("x size is",x.size)
print("x shape is",x.shape)

print("y size is",y.size)
print("y shape is",y.shape)

print()

print(np.matmul(x,y))
print(np.matmul(y,x))
print()

print(x[2][1])
print(y[2][1])
print()

print(x.max())
print(x.min())
print(x.min(axis = 0))

print()

print(np.mean(x))
print(np.median(x))


x size is 12
x shape is (3, 4)
y size is 12
y shape is (4, 3)

[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]]

10
8

12
1
[1 2 3 4]

6.5
6.5


## Exercise 3

Construct the square matrix 
$$
{\mathbf x} = \left(
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{matrix}
\right).
$$
Create a new matrix obtained as follows: add $-1$ to the entries in the first column, $0$ to those in the middle column and $+1$ to the entries in the last column. Find the transpose $x^T$ of the matrix $x$. Calculate the determinant of $x$. Calculate the trace of $x$. Get the three elements in the main diagonal. Get the two elements in each of the shorter diagonals - the one above and the one below the main diagonal. Find the rank of the matrix. Find the three eigenvalues $\lambda_i$. Verify explicitly that they are solutions to the characteristic equation 
$$
\det ({\mathbf x} - \lambda_i {\mathbf 1} ) = 0.
$$

In [ ]:
? np.add

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

new_x = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
print(new_x)
new_x = new_x + x
print(new_x)

print(np.transpose(x))
print(np.linalg.det(x))
print(np.trace(x))
print(np.diag(x))
print(np.diag(x,1))
print(np.diag(x,-1))

print(np.linalg.matrix_rank(x))
print(np.linalg.eigvals(x))
ident = np.identity(3)
chara = x - np.linalg.eigvals(x)[2]*ident
print(np.linalg.det(chara))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0
15
[1 5 9]
[2 6]
[4 8]
2
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
-1.5987211554602194e-14
