# More NumPy Exercises

Let's keep building on our basic numpy skills with the exercises below. If possible, use the numpy functions instead of native python code. 

In [ ]:
import numpy as np
np.random.seed(42) # This guarantees the code will generate the same set of random numbers whenever executed

## Exercise 1

Let's create two matrices

In [ ]:
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


Task 1: without running any code, write down on a piece of paper your prediction for the result from the following operation:

<b>first_matrix+second_matrix</b>

DO NOT CHEAT!

Task 2. Now execute the statement above and check your prediction.

In [ ]:
print(np.add(first_matrix,second_matrix))

[[2 4 6]
 [5 7 9]]


## Exercise 2

Let's create a common array to work with:

In [ ]:
np.random.seed(42) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=15, size=(3, 5))
random_integers

array([[ 7,  4, 13, 11,  8],
       [13,  5,  7, 10,  3],
       [ 7, 11, 11,  8,  5]])

Compute:

1. The average value of the entries in the second column
2. The maximum value in the second row
3. The minimum value in the third row
4. The location of the smallest value in the array


In [ ]:
print(np.mean(random_integers, axis=0)[1])
print(np.max(random_integers, axis=1)[1])
print(np.min(random_integers, axis=1)[2])
print(np.where(random_integers == np.min(random_integers)))

6.666666666666667
13
5
(array([1]), array([4]))


## Exercise 3. 

Consider the $3\times 5$ array a3by5 created below.

In [ ]:
a3by5 = np.random.random((3,5))
a3by5

array([[0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465]])

In [ ]:
a1by15 = a3by5.ravel()
a1by15.tolist
a1by15.sort
print(a1by15)


[0.60111501 0.70807258 0.02058449 0.96990985 0.83244264 0.21233911
 0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914
 0.61185289 0.13949386 0.29214465]


Flatten it into a list, sort the list and print it.


## Exercise 4.

Consider the arrays x, y and z below.

In [ ]:
x = np.array([-4, -3, -2, -1, 1, 2, 3, 4])
y = np.array([-3, -2, -1, 0, 1, 2, 3])
z = np.array([0, 0, 0, 0])
print(x)
print(y)
print(z)

[-4 -3 -2 -1  1  2  3  4]
[-3 -2 -1  0  1  2  3]
[0 0 0 0]


1. Write some code to test whether 
* at least one of the elements in the array is non-zero;
* all of the elements in the array are non-zero;
* at least one of the elements in the array is equal to zero;  

and apply it to each of the three arrays.

2. Add 5 to every positive entry in each array.

In [ ]:
def one_non_zero(a):
  return np.any(a != 0)
def all_non_zero(a):
  return np.all(a != 0)
def one_zero(a):
  return np.any(a == 0)

print(one_non_zero(x))
print(all_non_zero(x))
print(one_zero(x))
print()
print(one_non_zero(y))
print(all_non_zero(y))
print(one_zero(y))
print()
print(one_non_zero(z))
print(all_non_zero(z))
print(one_zero(z))
print()

True
True
False

True
False
True

False
False
True



In [ ]:
def add_5_to_pos(a):
  return np.where(a>0, a+5,a)
print(add_5_to_pos(x))
print()
print(add_5_to_pos(y))
print()
print(add_5_to_pos(z))
print()

[-4 -3 -2 -1  6  7  8  9]

[-3 -2 -1  0  6  7  8]

[0 0 0 0]



## Exercise 5

Consider the Pauli matrices defined below.

$$
\left(
\begin{matrix}
0 & 1 \\
1 & 0
\end{matrix}
\right),
\left(
\begin{matrix}
0 & -i \\
i & 0
\end{matrix}
\right),
\left(
\begin{matrix}
1 & 0 \\
0 & -1
\end{matrix}
\right)
$$

1. Verify that they are traceless
2. Verify that they all have determinants -1.
3. Verify that they are Hermitian.
4. Verify that they are unitary.
5. Verify the SU(2) algebra, i.e., the commutation relations among the Pauli matrices. If you don't remember the formulas, derive them.


In [ ]:
sigX = np.matrix([[0+0j,1+0j],[1+0j,0+0j]])
sigY = np.matrix([[0+0j,0-1j],[0+1j,0+0j]])
sigZ = np.matrix([[1+0j,0+0j],[0+0j,-1+0j]])
print(sigX) 
print(sigY)
print(sigZ)

[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


In [ ]:
print(np.trace(sigX))
print(np.trace(sigY))
print(np.trace(sigZ))
print()

print(np.linalg.det(sigX))
print(np.linalg.det(sigY))
print(np.linalg.det(sigZ))
print()

print(sigX == np.conj(np.transpose(sigX)))
print(sigY == np.conj(np.transpose(sigY)))
print(sigZ == np.conj(np.transpose(sigZ)))
print()

print(sigX == np.linalg.inv(np.conj(np.transpose(sigX))))
print(sigY == np.linalg.inv(np.conj(np.transpose(sigY))))
print(sigZ == np.linalg.inv(np.conj(np.transpose(sigZ))))
print()

def commuator (a,b):
  return a@b-b@a

print(commuator(sigX,sigY) == 2*1j*sigZ)
print(commuator(sigY,sigZ) == 2*1j*sigX)
print(commuator(sigZ,sigX) == 2*1j*sigY)
print(commuator(sigX,sigX) == 0)

0j
0j
0j

(-1+0j)
(-1+0j)
(-1+0j)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
